// The contract for our AI inference service.
// This file defines the methods and message structures.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: pkg/inference/inference.proto

package inference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the prompt.
type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_pkg_inference_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inference_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_inference_inference_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// The response message containing the model's generated text.
type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedText string                 `protobuf:"bytes,1,opt,name=generated_text,json=generatedText,proto3" json:"generated_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_pkg_inference_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_inference_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_inference_inference_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateResponse) GetGeneratedText() string {
	if x != nil {
		return x.GeneratedText
	}
	return ""
}

var File_pkg_inference_inference_proto protoreflect.FileDescriptor

const file_pkg_inference_inference_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/inference/inference.proto\x12\tinference\")\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"9\n" +
	"\x10GenerateResponse\x12%\n" +
	"\x0egenerated_text\x18\x01 \x01(\tR\rgeneratedText2W\n" +
	"\n" +
	"Inferencer\x12I\n" +
	"\fGenerateText\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse\"\x00B@Z>github.com/lao-tseu-is-alive/go-cloud-grpc-client-ai/inferenceb\x06proto3"

var (
	file_pkg_inference_inference_proto_rawDescOnce sync.Once
	file_pkg_inference_inference_proto_rawDescData []byte
)

func file_pkg_inference_inference_proto_rawDescGZIP() []byte {
	file_pkg_inference_inference_proto_rawDescOnce.Do(func() {
		file_pkg_inference_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_inference_inference_proto_rawDesc), len(file_pkg_inference_inference_proto_rawDesc)))
	})
	return file_pkg_inference_inference_proto_rawDescData
}

var file_pkg_inference_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_inference_inference_proto_goTypes = []any{
	(*GenerateRequest)(nil),  // 0: inference.GenerateRequest
	(*GenerateResponse)(nil), // 1: inference.GenerateResponse
}
var file_pkg_inference_inference_proto_depIdxs = []int32{
	0, // 0: inference.Inferencer.GenerateText:input_type -> inference.GenerateRequest
	1, // 1: inference.Inferencer.GenerateText:output_type -> inference.GenerateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_inference_inference_proto_init() }
func file_pkg_inference_inference_proto_init() {
	if File_pkg_inference_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_inference_inference_proto_rawDesc), len(file_pkg_inference_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_inference_inference_proto_goTypes,
		DependencyIndexes: file_pkg_inference_inference_proto_depIdxs,
		MessageInfos:      file_pkg_inference_inference_proto_msgTypes,
	}.Build()
	File_pkg_inference_inference_proto = out.File
	file_pkg_inference_inference_proto_goTypes = nil
	file_pkg_inference_inference_proto_depIdxs = nil
}
