// The contract for our AI inference service.
// This file defines the methods and message structures.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pkg/inference/inference.proto

package inference

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inferencer_GenerateText_FullMethodName = "/inference.Inferencer/GenerateText"
)

// InferencerClient is the client API for Inferencer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition.
type InferencerClient interface {
	// A method to generate text using a large language model.
	GenerateText(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
}

type inferencerClient struct {
	cc grpc.ClientConnInterface
}

func NewInferencerClient(cc grpc.ClientConnInterface) InferencerClient {
	return &inferencerClient{cc}
}

func (c *inferencerClient) GenerateText(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, Inferencer_GenerateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferencerServer is the server API for Inferencer service.
// All implementations must embed UnimplementedInferencerServer
// for forward compatibility.
//
// The service definition.
type InferencerServer interface {
	// A method to generate text using a large language model.
	GenerateText(context.Context, *GenerateRequest) (*GenerateResponse, error)
	mustEmbedUnimplementedInferencerServer()
}

// UnimplementedInferencerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferencerServer struct{}

func (UnimplementedInferencerServer) GenerateText(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateText not implemented")
}
func (UnimplementedInferencerServer) mustEmbedUnimplementedInferencerServer() {}
func (UnimplementedInferencerServer) testEmbeddedByValue()                    {}

// UnsafeInferencerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferencerServer will
// result in compilation errors.
type UnsafeInferencerServer interface {
	mustEmbedUnimplementedInferencerServer()
}

func RegisterInferencerServer(s grpc.ServiceRegistrar, srv InferencerServer) {
	// If the following call pancis, it indicates UnimplementedInferencerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inferencer_ServiceDesc, srv)
}

func _Inferencer_GenerateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferencerServer).GenerateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inferencer_GenerateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferencerServer).GenerateText(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inferencer_ServiceDesc is the grpc.ServiceDesc for Inferencer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inferencer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.Inferencer",
	HandlerType: (*InferencerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateText",
			Handler:    _Inferencer_GenerateText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/inference/inference.proto",
}
